### ISSUE TITLE
Anti-Releak

### ISSUE THREAD

**Issue by LeakMania-v6** [HSGamer/list-of-shame-mcvn#15]
`"Cracked" plugin (BlackSpigot, DirectLeaks, LeakMania,...)`
`Chính sách Anti-Releak của các trang đôi khi lại gây ảnh hưởng cho một số server (Ví dụ, Ví dụ 2,...)`
Don't want to be banned by our anti-releak, don't releak.
It's simple as that.

**Comment by Haizive** [comment]
Sites like DirectLeaks, LeakMania have Anti-Releak just because of people reposting/releaking resources on some other random sites, That is against rules on all sites, so they have Anti-Releak to combat that.

**Comment by HSGamer** [comment]
All of them are temporary solutions for using premium plugins. I won't recommend them anyway.
I was in a period when Anti-Releak in some sites was buggy.
Better be aware.

**Comment by LeakMania-v6** [comment]
It is only buggy if you try to bypass it.

**Comment by HSGamer** [comment]
> It is only buggy if you try to bypass it.

You may be correct.
One other case is that you don't update the plugins after some times. Could be the Anti-Releak system being updated.

**Comment by LeakMania-v6** [comment]
The Anti-Releak system is completely separated the the plugin update system.
When we found a update system that disable the plugin if it is not up-to-date, we removing the update system.
You will only find that problem on BSMC because their staff has no cracking skills.

**Comment by LeakMania-v6** [comment]
Btw, you say that LM is a shame but you using it:
![1](https://user-images.githubusercontent.com/48015201/115996902-6d9a8580-a5e1-11eb-996b-e8587faedc73.png)

**Comment by LeakMania-v6** [comment]
Please approve it:
https://github.com/HSGamer/list-of-shame-mcvn/compare/main...LeakMania-v6:patch-1

**Comment by HSGamer** [comment]
> Btw, you say that LM is a shame but you using it:
> ![1](https://user-images.githubusercontent.com/48015201/115996902-6d9a8580-a5e1-11eb-996b-e8587faedc73.png)

Used to. Why should I not login back to see my account after a long time? If you want, you can delete my account.

**Comment by LeakMania-v6** [comment]
> > Btw, you say that LM is a shame but you using it:
> > ![1](https://user-images.githubusercontent.com/48015201/115996902-6d9a8580-a5e1-11eb-996b-e8587faedc73.png)
> 
> Used to. Why should I not login back to see my account after a long time?
That's not a problem, but don't say it's a shame if you use it, it's not logic.

> If you want, you can delete my account.
If you're sure that you want it to be removed, you need to open a ticket on the site.

**Comment by HSGamer** [comment]
> The Anti-Releak system is completely separated the the plugin update system.
> When we found a update system that disable the plugin if it is not up-to-date, we removing the update system.
> You will only find that problem on BSMC because their staff has no cracking skills.

Those "downloaders from releakers" don't know what they are doing and still ask us why their servers shut down.

BSMC is the one to say. I hate that site.

This is for a community with those newbie Vietnamese people make their servers with no skills and little knowledge on what they are doing.

Like I said, "A temporary solution but risky in long-term".

You have your reason for Anti-Releak, and you care about your users. I appreciate that. But I don't know other sites, besides you (and possibly DL), are doing what you are doing.

**Comment by LeakMania-v6** [comment]
> > The Anti-Releak system is completely separated the the plugin update system.
> > When we found a update system that disable the plugin if it is not up-to-date, we removing the update system.
> > You will only find that problem on BSMC because their staff has no cracking skills.
> 
> Those "downloaders from releakers" don't know what they are doing and still ask us why their servers shut down.

The server is shutting down because you downloaded a releaked version of the plugin.
If you download it directly from LM and you not share the file anywhere, you will not have this problem.

> BSMC is the one to say. I hate that site.

I not specifically hate BSMC but the staff are skids.

> This is for a community with those newbie Vietnamese people make their servers with no skills and little knowledge on what they are doing.

So, instead of releaking the file on MCVN, add the LM link to the resource to allow them to directly download the files on LM.

> Like I said, "A temporary solution but risky in long-term".

The goal of LM is only to allow our members to test premium plugins before buying them because on majors premium plugins there is no trial versions.
We never said to our members to use them in production (it's possible, but it's better to puchase the plugin to support the plugin author).

> You have your reason for Anti-Releak, and you care about your users. I appreciate that. But I don't know other sites, besides you (and possibly DL), are doing what you are doing.

Yes we need it, else peoples are reuploading our content on others site and claiming that the plugins has been cracked by them without quoting us.
