### ISSUE TITLE
Thế hệ Member mới - Lười và không biết tiếp thu

### ISSUE THREAD

**Issue by tienthanh23423** [HSGamer/list-of-shame-mcvn#20]
| Thế hệ member mới thật đáng thất vọng
- Lười
- Không biết tiếp thu
- Chẳng chịu tìm kiếm thông tin
- Đút tận họng vẫn không hề tìm kiếm
- Trẻ trâu, bị chửi để khôn thì chửi lại.

**Comment by acayrin** [comment]
lol more like personal issue

**Comment by TinLite** [comment]
Chào mừng đến với Minecraft.

**Comment by HSGamer** [comment]
này giống kiểu `Google có mà`
và cái vấn đề này khá rộng cho toàn cái internet này, không chỉ Minecraft đâu

**Comment by tienthanh23423** [comment]
> lol more like personal issue

what a nice day to get this quote.

**Comment by JustMangoT** [comment]
https://github.com/HSGamer/list-of-shame-mcvn#ki%E1%BA%BFn-th%E1%BB%A9c-ch%C3%A9m-gi%C3%B3

**Comment by MiniFlex** [comment]
Nói nhiều làm ít
