### ISSUE TITLE
được chỉ thẳng mặt 1 cá nhân vì đóng góp ngu dốt và sự phá hoại của nó trong cộng đồng ko ? 

### ISSUE THREAD

**Issue by TypicalShavonne** [HSGamer/list-of-shame-mcvn#24]

**Comment by minhh2792** [comment]
😳

**Comment by HSGamer** [comment]
Nếu thật sự cộng đồng cho là người này có những việc "gây tranh cãi" thì có thể đem lên (cái này cần cả cộng đồng xác nhận).
Còn nếu người này không đáng để đem nhưng lại cố tình đem lên để công kích người đó thì đây sẽ không duyệt.
