### ISSUE TITLE
tế spigotmc lên

### ISSUE THREAD

**Issue by TypicalShavonne** [HSGamer/list-of-shame-mcvn#25]
dạo này, spigotmc bị nu lo hay sao
https://cdn.discordapp.com/attachments/861681423110766622/888849144570073139/image0.png
https://cdn.discordapp.com/attachments/861681423110766622/888864832013619220/Screenshot_2021-09-18_at_20.11.16.png
Dev của EcoEnchants, bị mod/staff j đó của spigot, ép gỡ đoạn code recommend users chuyển qua PaperMC xài
ủa ? 
Xong nọ, dev của TAB bị spigot ban acc vì gắn link dẫn tới cái bản pre của plugin TAB trong cái post plugin của ổng(Nghe phong phanh v, giờ TAB lên github open source luôn r)
**đang đua nhau qua polymart xài =))**

**Comment by minhh2792** [comment]
https://mineacademy.org/the-death-of-spigotmc/

**Comment by HSGamer** [comment]
https://github.com/PaperMC/PaperLib/issues/41

**Comment by HSGamer** [comment]
Cái này mỗi list of shame lại có một góc nhìn.
Và nó chung cho cả cộng đồng thế giới nên quá rộng cho cái list of shame này.
