### ISSUE TITLE
Quá nhiều server open cùng một file

### ISSUE THREAD

**Issue by tienthanh23423** [HSGamer/list-of-shame-mcvn#3]
Quá nhiều server open cùng một file
> Mua hoặc download một file, rồi đem về bỏ vào server mình, rồi đăng lên diễn đàn đễ quảng cáo

Thật ra thì nếu các bạn nghĩ là chỉ có những người mới vào làm điều này, bạn hơi sai rồi, đáng tiếc là đến cả Grassminevn còn làm thế mà. Nếu nhớ không nhầm thì hồi lâu rồi có thấy ai đó đăng cái file digitalmc lên minecraftvn.net. Mà giờ thằng nào đó làm bên Grassminevn lại còn dùng nó để up làm server. Nó kêu là file đó của nó, nhưng mà file đó lên mạng rồi, chả còn bản quyền gì nữa.

**Comment by HSGamer** [comment]
có thể dùng câu gì đó để nói chung cho tất cả server

**Comment by tienthanh23423** [comment]
chú chỉnh lại của ta cũng có vẻ hay đó, ta ko còn làm nhiều về mc nên chả nhớ các từ hay
