### ISSUE TITLE
Những người thích "gáy"

### ISSUE THREAD

**Issue by tienthanh23423** [HSGamer/list-of-shame-mcvn#4]
Những người thích "gáy"
> Luôn tỏ vẻ mình rất giỏi (có giỏi thiệt) bằng việc đi chửi (có khi chửi những thứ chả cần chửi) nhưng khi bị cứng họng thì chả hó hé được gì

Cho rằng mình giỏi và đi chửi => não phẳng
Làm cho các member mới căng thẳng.
Các member lâu năm thì ghét cay ghét đắng
Mình không nói chính xác ai ở đây, bạn nào nghĩ là mình thì tự biết

**Comment by HSGamer** [comment]
Đây là thực trạng của toàn bộ cái facebook việt nam, không riêng gì cộng đồng Minecraft... nên vấn đề này vượt quá tầm của danh sách này

**Comment by tienthanh23423** [comment]
ok
